FROM openjdk:11
WORKDIR /
ADD target/calculate-networth-service-0.0.1-SNAPSHOT.jar calculate-networth-service-0.0.1-SNAPSHOT.jar
EXPOSE 8200
CMD java -jar calculate-networth-service-0.0.1-SNAPSHOT.jar